[package]
name = "scalatest-watcher"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
config = "0.15.11"
junit-parser = "1.4.0"
notify = "8.0.0"
serde = { version = "1.0.219", features = ["derive"] }
walkdir = "2.5.0"
